apiVersion: apps/v1
kind: Deployment
metadata:
  name: weatherforecastapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: weatherforecastapi
  template:
    metadata:
      labels:
        app: weatherforecastapi
    spec:
      containers:
        - name: weatherforecastapi
          imagePullPolicy: IfNotPresent
          image: weatherforecastapi
          ports:
            - containerPort: 80
